[ids]
*

[main]
rightalt = overload(altgr, A-M-d)

[altgr]
space = A-M-d

[altgr+control+meta]
leftbrace = macro(C-S-u 201c space)
rightbrace = macro(C-S-u 2018 space)
backslash = macro(C-S-u 2013 space)
apostrophe = macro(C-S-u 2032 space)

[altgr+control+meta+shift]
leftbrace = macro(C-S-u 201d space)
rightbrace = macro(C-S-u 2019 space)
backslash = macro(C-S-u 2014 space)
apostrophe = macro(C-S-u 2033 space)
